builds:
  - id: tailscaled
    main: ./cmd/tailscaled
    binary: tailscaled
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: tailscale
    main: ./cmd/tailscale
    binary: tailscale
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
